GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUnlhbiIsImlhdCI6MTYzNTA4MjA4MCwiZXhwIjoxNjM1MDgyMDk1fQ.yUpJdiMimpCnhPjIh9uW2a_WqW4TYQnGSr5ndP675gs

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUnlhbiIsImlhdCI6MTYzNTA4MjI2Mn0.vxiK7m7mi6Oi0lqgsDcztY7wG4kPkU43DveXg_h1Ks0"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUnlhbiIsImlhdCI6MTYzNTA4MjI2Mn0.vxiK7m7mi6Oi0lqgsDcztY7wG4kPkU43DveXg_h1Ks0"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Ryan"
}